/* ============================================
   Export Module — PDF & Excel Generation
   ============================================ */
const Export = (() => {

    /**
     * Export loan details as a simple text report (downloadable)
     * For PDF, we generate an HTML page and use window.print()
     */

    // ── PDF Translation Dictionary ─────────────────────────────────────────────
    const _pdfDict = {
        en: {
            loanReport: 'LOAN REPORT', loanId: 'Loan ID', date: 'Date', status: 'Status',
            customerDetails: 'Customer Details', customerName: 'Customer Name', mobile: 'Mobile Number', address: 'Address',
            goldDetails: 'Gold Details', metalType: 'Metal Type', purity: 'Purity', weight: 'Weight', locker: 'Locker No.', currentValue: 'Current Metal Value',
            loanDetails: 'Loan Details', loanAmount: 'Loan Amount', interestRate: 'Interest Rate', interestType: 'Interest Type',
            startDate: 'Start Date', maturityDate: 'Maturity Date', duration: 'Duration', months: 'Months',
            paymentSummary: 'Payment Summary', totalInterest: 'Total Interest (so far)', paidInterest: 'Paid Interest',
            remainingInterest: 'Remaining Interest', totalPayable: 'Total Payable Amount',
            loanLedger: 'Loan Ledger Details', dateCol: 'Date', particularsCol: 'Particulars',
            debitCol: 'Debit (₹)', interestCol: 'Interest (₹)', creditCol: 'Credit (₹)', netPayableCol: 'Net Payable (₹)',
            totalRow: 'Total', settleDetails: 'Settlement Details', totalAmount: 'Total Amount',
            paidAmount: 'Paid Amount', discountGiven: 'Discount Given', finalStatus: 'Final Status',
            termsTitle: 'Important Information',
            terms: ['Interest is calculated on monthly basis.', 'Late payment may attract additional charges.', 'Gold will be returned only after full payment.'],
            sigCustomer: 'Customer Signature', sigAuth: 'Authorized Signature',
            footer: 'This report is generated by GoldVault Finance Loan Management System.',
            reportTime: 'Report generated at',
            simple: 'Simple', compound: 'Compound', gold: 'Gold', silver: 'Silver',
            active: 'ACTIVE', closed: 'CLOSED', migrated: 'MIGRATED',
            loanIssued: 'Gold Loan Issued', paymentReceived: 'Payment Received',
            discountEntry: 'Discount Given', loanSettled: 'Loan Settled'
        },
        hi: {
            loanReport: 'लोन रिपोर्ट', loanId: 'लोन आईडी', date: 'दिनांक', status: 'स्थिति',
            customerDetails: 'ग्राहक विवरण', customerName: 'नाम', mobile: 'मोबाइल नंबर', address: 'पता',
            goldDetails: 'सोने का विवरण', metalType: 'धातु का प्रकार', purity: 'शुद्धता (पोरिटी)', weight: 'वजन', locker: 'लॉकर नंबर', currentValue: 'वर्तमान सोने का मूल्य',
            loanDetails: 'लोन का विवरण', loanAmount: 'लोन राशि', interestRate: 'ब्याज दर', interestType: 'ब्याज प्रकार',
            startDate: 'लोन प्रारंभ तिथि', maturityDate: 'परिपक्वता तिथि', duration: 'अवधि', months: 'महीने',
            paymentSummary: 'भुगतान सारांश', totalInterest: 'कुल ब्याज (अब तक)', paidInterest: 'चुकाया गया ब्याज',
            remainingInterest: 'शेष ब्याज', totalPayable: 'कुल देय राशि',
            loanLedger: 'लोन लेजर विवरण', dateCol: 'दिनांक', particularsCol: 'विवरण',
            debitCol: 'डेबिट (₹)', interestCol: 'ब्याज (₹)', creditCol: 'क्रेडिट (₹)', netPayableCol: 'कुल बकाया (₹)',
            totalRow: 'कुल', settleDetails: 'निपटान विवरण', totalAmount: 'कुल राशि',
            paidAmount: 'भुगतान राशि', discountGiven: 'दी गई छूट', finalStatus: 'अंतिम स्थिति',
            termsTitle: 'महत्वपूर्ण जानकारी',
            terms: ['ब्याज की गणना मासिक आधार पर की जाती है।', 'देय तिथि के बाद भुगतान करने पर अतिरिक्त शुल्क लागू हो सकता है।', 'पूर्ण भुगतान के बाद ही सोना वापस किया जाएगा।'],
            sigCustomer: 'ग्राहक हस्ताक्षर', sigAuth: 'अधिकृत हस्ताक्षर',
            footer: 'यह रिपोर्ट गोल्डवॉल्ट फाइनेंस लोन मैनेजमेंट सिस्टम द्वारा जनरेट की गई है।',
            reportTime: 'रिपोर्ट जनरेट समय',
            simple: 'साधारण (Simple)', compound: 'चक्रवृद्धि (Compound)', gold: 'सोना (Gold)', silver: 'चाँदी (Silver)',
            active: 'ACTIVE', closed: 'CLOSED', migrated: 'MIGRATED',
            loanIssued: 'गोल्ड लोन जारी', paymentReceived: 'भुगतान प्राप्त',
            discountEntry: 'छूट दी गई', loanSettled: 'ऋण निपटान'
        }
    };

    function _pdfT(lang) { return _pdfDict[lang] || _pdfDict.en; }

    function _translateRow(text, t) {
        const map = {
            'Gold Loan Issued': t.loanIssued, 'Silver Loan Issued': t.loanIssued,
            'Payment Received': t.paymentReceived, 'Partial Payment': t.paymentReceived,
            'Discount Given': t.discountEntry, 'Loan Settled': t.loanSettled
        };
        for (const [en, tr] of Object.entries(map)) {
            if (text && text.includes(en)) return text.replace(en, tr);
        }
        return text || '—';
    }

    function _cur(n) {
        const v = parseFloat(n) || 0;
        return '₹' + v.toLocaleString('en-IN', { maximumFractionDigits: 0 });
    }

    function getLoanReportHTML(loan, details, settings, lang) {
        lang = lang || ((typeof I18n !== 'undefined') ? I18n.getLang() : 'en');
        const t = _pdfT(lang);
        const isHi = lang === 'hi';
        const font = isHi
            ? "'Noto Sans Devanagari', 'Arial Unicode MS', Arial, sans-serif"
            : "'Inter', Arial, sans-serif";

        const shopName   = settings.shopName    || 'GOLD VAULT FINANCE';
        const shopAddr   = settings.shopAddress || '';
        const shopPhone  = settings.shopPhone   || '';
        const shopLogo   = settings.shopLogo    || settings.logoUrl || '';
        const statusLabel= loan.isMigrated ? t.migrated : (loan.status === 'closed' ? t.closed : t.active);
        const statusColor= loan.status === 'closed' ? '#dc2626' : '#059669';

        // Items table rows
        const items = loan.items || [];
        const totalWeight = items.length > 0
            ? items.reduce((s, it) => s + (parseFloat(it.weightGrams) || 0), 0)
            : (parseFloat(loan.weightGrams) || 0);
        const purityDisplay = items.length > 0
            ? [...new Set(items.map(i => i.purity))].join(', ')
            : (loan.metalSubType || '—');

        // Ledger rows
        const ledger = loan.loanLedger || [];
        const origPrincipal = loan.originalLoanAmount || loan.loanAmount || 0;
        const annualRate = details.annualRate || 0;
        const basis = details.basis || 360;
        let totalDebit = 0, totalInterest = 0, totalCredit = 0;
        const ledgerRows = ledger.map((e, idx) => {
            totalDebit    += (parseFloat(e.debit)    || 0);
            totalInterest += (parseFloat(e.interest) || 0);
            totalCredit   += (parseFloat(e.credit)   || 0);

            let days = 0;
            if (idx > 0 && e.date && ledger[idx-1].date) {
                const start = new Date(ledger[idx-1].date);
                const end = new Date(e.date);
                start.setHours(0,0,0,0);
                end.setHours(0,0,0,0);
                days = Math.max(0, Math.ceil((end - start) / (1000 * 60 * 60 * 24)));
            }

            const d = e.debit   > 0 ? _cur(e.debit)    : '—';
            let i = '—';
            if ((e.interest||0) > 0) {
                // Reverse calculate to match exact interest charged
                const principal = idx > 0 ? (ledger[idx - 1].balance || origPrincipal) : origPrincipal;
                if (principal > 0 && annualRate > 0) {
                    days = Math.round((e.interest * basis) / (principal * (annualRate / 100)));
                }
                const daysLabel = isHi ? `(${days} दिन)` : `(${days} days)`;
                i = `${_cur(e.interest)} <span style="font-size:10px;color:#777;margin-left:4px;font-weight:600;white-space:nowrap;">${daysLabel}</span>`;
            }

            const c = e.credit  > 0 ? _cur(e.credit)   : '—';
            const b = e.balance != null ? _cur(e.balance) : '—';
            const rowTxt = _translateRow(e.particulars || '', t);
            const bgr = e.type === 'loan' ? 'background:#f0f9ff;' : '';
            return `<tr style="${bgr}">
                <td>${e.date ? new Date(e.date).toLocaleDateString('en-IN') : '—'}</td>
                <td>${rowTxt}</td>
                <td style="color:#dc2626;font-weight:600;">${d}</td>
                <td style="color:#d97706;font-weight:600;white-space:nowrap;">${i}</td>
                <td style="color:#059669;font-weight:600;">${c}</td>
                <td style="font-weight:700;color:#1e3a5f;">${b}</td>
            </tr>`;
        }).join('');

        // Settlement section
        const settleSec = (loan.status === 'closed' && loan.settlement) ? `
        <div style="margin-top:16px;padding:14px;background:#f0fdf4;border-radius:8px;border:1px solid #bbf7d0;">
            <div style="font-size:13px;font-weight:800;color:#059669;margin-bottom:8px;">🤝 ${t.settleDetails}</div>
            <table style="width:100%;font-size:12px;"><tr>
                <td style="padding:4px 0;color:#4b5563;">${t.totalAmount}</td><td style="font-weight:700;">${_cur(loan.settlement.totalAmount)}</td>
                <td style="padding:4px 0;color:#4b5563;">${t.paidAmount}</td><td style="font-weight:700;color:#d97706;">${_cur(loan.settlement.paidAmount)}</td>
                ${loan.settlement.discount > 0 ? `<td style="padding:4px 0;color:#4b5563;">${t.discountGiven}</td><td style="color:#dc2626;font-weight:700;">${_cur(loan.settlement.discount)}</td>` : ''}
            </tr></table>
        </div>` : '';

        const now = new Date();
        const nowStr = `${now.toLocaleDateString('en-IN')}, ${now.toLocaleTimeString('en-IN', {hour:'2-digit',minute:'2-digit'})} ${isHi ? 'PM' : ''}`;

        return `
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&family=Noto+Sans+Devanagari:wght@400;600;700;800&display=swap');
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { font-family: ${font}; background: #fff; color: #1a1a2e; }
        .wrap { max-width: 780px; margin: 0 auto; padding: 24px 28px; }
        /* Shop Header */
        .shop-hdr { text-align:center; border-bottom: 3px solid #d4af37; padding-bottom: 14px; margin-bottom: 18px; }
        .shop-hdr img { max-height:52px; margin-bottom:6px; }
        .shop-title { font-size:22px; font-weight:900; color:#1e3a5f; letter-spacing:1px; }
        .shop-title span { color:#d4af37; }
        .shop-sub { font-size:12px; color:#4b5563; margin-top:4px; line-height:1.6; }
        /* Report title */
        .rpt-title { text-align:center; font-size:${isHi?'22px':'20px'}; font-weight:800; color:#1e3a5f; margin:10px 0; letter-spacing:.5px; }
        .rpt-title-bar { display:flex; align-items:center; justify-content:center; gap:12px; margin-bottom:14px; }
        .rpt-title-bar hr { flex:1; border:none; border-top:2px solid #d4af37; }
        /* Meta row */
        .meta { display:flex; justify-content:flex-end; gap:24px; font-size:11.5px; margin-bottom:14px; }
        .meta span { color:#4b5563; } .meta b { color:#1e3a5f; }
        .meta .stat { color:${statusColor}; font-weight:800; }
        /* Section */
        .sec { margin-bottom:14px; }
        .sec-title { font-size:12px; font-weight:800; color:#1e3a5f; background:#eef2ff; padding:5px 10px; border-left:3px solid #4f46e5; border-radius:0 4px 4px 0; margin-bottom:8px; }
        .sec-title.gold { background:#fefce8; border-left-color:#d4af37; }
        table.info { width:100%; border-collapse:collapse; font-size:12px; }
        table.info td { padding:4px 8px; vertical-align:top; }
        table.info td:first-child { color:#6b7280; width:42%; }
        table.info td:nth-child(2) { color:#374151; width:5%; text-align:center; }
        table.info td:last-child { font-weight:600; color:#1e3a5f; }
        /* Two-col grid */
        .two-col { display:grid; grid-template-columns:1fr 1fr; gap:14px; margin-bottom:14px; }
        /* Payment boxes */
        .pay-grid { display:grid; grid-template-columns:repeat(4,1fr); gap:10px; margin-bottom:14px; }
        .pay-box { text-align:center; border:1px solid #e5e7eb; border-radius:8px; padding:10px 6px; }
        .pay-box .lbl { font-size:10.5px; color:#6b7280; margin-bottom:4px; line-height:1.3; }
        .pay-box .val { font-size:15px; font-weight:800; color:#1e3a5f; }
        .pay-box.total { background:#f0fdf4; border-color:#bbf7d0; }
        .pay-box.total .lbl { color:#059669; }
        .pay-box.total .val { color:#059669; font-size:18px; }
        /* Ledger table */
        table.ledger { width:100%; border-collapse:collapse; font-size:11.5px; margin-bottom:14px; }
        table.ledger thead tr { background:#1e3a5f; color:#fff; }
        table.ledger thead th { padding:7px 6px; text-align:left; font-weight:700; font-size:11px; }
        table.ledger tbody tr:nth-child(even) { background:#f8fafc; }
        table.ledger tbody td { padding:5px 6px; border-bottom:1px solid #e5e7eb; vertical-align:middle; }
        table.ledger tfoot tr { background:#eef2ff; font-weight:700; font-size:12px; }
        table.ledger tfoot td { padding:6px 6px; }
        /* Terms */
        .terms { background:#fffbeb; border:1px solid #fde68a; border-radius:6px; padding:10px 14px; margin-bottom:14px; font-size:11.5px; }
        .terms .t-title { font-weight:800; color:#92400e; margin-bottom:6px; }
        .terms ul { padding-left:16px; color:#78350f; line-height:1.8; }
        /* Signatures */
        .sig-row { display:flex; justify-content:space-between; align-items:flex-end; margin-top:20px; }
        .sig-box { text-align:center; width:200px; }
        .sig-line { border-top:1.5px solid #1e3a5f; margin-bottom:4px; }
        .sig-label { font-size:12px; font-weight:700; color:#1e3a5f; }
        .seal { text-align:center; }
        .seal-circle { width:60px; height:60px; border:2.5px solid #d4af37; border-radius:50%; display:inline-flex; align-items:center; justify-content:center; font-size:14px; font-weight:900; color:#1e3a5f; letter-spacing:-1px; }
        /* Footer */
        .footer { text-align:center; font-size:10.5px; color:#9ca3af; border-top:1px solid #e5e7eb; padding-top:10px; margin-top:14px; line-height:1.8; }
        @media print { body { -webkit-print-color-adjust:exact; print-color-adjust:exact; } }
    </style>
    <div class="wrap">

        <!-- Shop Header -->
        <div class="shop-hdr">
            ${shopLogo ? `<img src="${shopLogo}" alt="Logo"><br>` : ''}
            <div class="shop-title">${shopName.includes(' ') ? shopName.replace(/ (\S+)$/, ' <span>$1</span>') : shopName}</div>
            ${shopAddr ? `<div class="shop-sub">${shopAddr}${shopPhone ? ` | फोन: +91 ${shopPhone}` : ''}</div>` : ''}
        </div>

        <!-- Report Title -->
        <div class="rpt-title-bar">
            <hr><div class="rpt-title">❀ ${t.loanReport} ❀</div><hr>
        </div>

        <!-- Meta -->
        <div class="meta">
            <div><span>${t.loanId} : </span><b>${loan.id || '—'}</b></div>
            <div><span>${t.date} : </span><b>${new Date().toLocaleDateString('en-IN')}</b></div>
            <div><span>${t.status} : </span><b class="stat">${statusLabel}</b></div>
        </div>

        <!-- Customer Details -->
        <div class="sec">
            <div class="sec-title">👤 ${t.customerDetails}</div>
            <table class="info">
                <tr><td>${t.customerName}</td><td>:</td><td>${loan.customerName || '—'}</td></tr>
                <tr><td>${t.mobile}</td><td>:</td><td>${loan.mobile || '—'}</td></tr>
                ${loan.address ? `<tr><td>${t.address}</td><td>:</td><td>${loan.address}</td></tr>` : ''}
            </table>
        </div>

        <!-- Gold + Loan Details -->
        <div class="two-col">
            <div class="sec">
                <div class="sec-title gold">🏅 ${t.goldDetails}</div>
                <table class="info">
                    <tr><td>${t.metalType}</td><td>:</td><td>${loan.metalType === 'gold' ? t.gold : t.silver}</td></tr>
                    <tr><td>${t.purity}</td><td>:</td><td>${purityDisplay}</td></tr>
                    <tr><td>${t.weight}</td><td>:</td><td>${totalWeight.toFixed(2)} ${isHi ? 'ग्राम' : 'grams'}</td></tr>
                    <tr><td>${t.locker}</td><td>:</td><td>${loan.lockerName || loan.lockerNo || '—'}</td></tr>
                    <tr><td colspan="3" style="padding-top:6px;">
                        <div style="background:#fefce8;border:1px solid #fde68a;border-radius:6px;padding:6px 10px;display:flex;justify-content:space-between;">
                            <span style="color:#92400e;font-size:11px;font-weight:700;">${t.currentValue}</span>
                            <span style="color:#92400e;font-size:15px;font-weight:800;">${_cur(details.metalValue)}</span>
                        </div>
                    </td></tr>
                </table>
            </div>
            <div class="sec">
                <div class="sec-title">💰 ${t.loanDetails}</div>
                <table class="info">
                    <tr><td>${t.loanAmount}</td><td>:</td><td style="color:#1e3a5f;font-size:14px;font-weight:800;">${_cur(loan.loanAmount)}</td></tr>
                    <tr><td>${t.interestRate}</td><td>:</td><td>${loan.interestRate}% ${isHi ? 'प्रति माह' : 'per month'}</td></tr>
                    <tr><td>${t.interestType}</td><td>:</td><td>${loan.interestType === 'compound' ? t.compound : t.simple}</td></tr>
                    <tr><td>${t.startDate}</td><td>:</td><td>${new Date(loan.loanStartDate).toLocaleDateString('en-IN')}</td></tr>
                    <tr><td>${t.maturityDate}</td><td>:</td><td>${new Date(details.maturityDate).toLocaleDateString('en-IN')}</td></tr>
                    <tr><td>${t.duration}</td><td>:</td><td>${loan.loanDuration || 12} ${t.months}</td></tr>
                </table>
            </div>
        </div>

        <!-- Payment Summary -->
        <div class="sec">
            <div class="sec-title">💳 ${t.paymentSummary}</div>
            <div class="pay-grid">
                <div class="pay-box"><div class="lbl">${t.totalInterest}</div><div class="val">${_cur(details.totalInterest)}</div></div>
                <div class="pay-box"><div class="lbl">${t.paidInterest}</div><div class="val">${_cur(details.paidInterest || 0)}</div></div>
                <div class="pay-box"><div class="lbl">${t.remainingInterest}</div><div class="val">${_cur(details.remainingInterest || 0)}</div></div>
                <div class="pay-box total"><div class="lbl">${t.totalPayable}</div><div class="val">${_cur(details.totalPayable)}</div></div>
            </div>
        </div>

        ${settleSec}

        <!-- Loan Ledger -->
        ${ledger.length > 0 ? `
        <div class="sec">
            <div class="sec-title">📋 ${t.loanLedger}</div>
            <table class="ledger">
                <thead><tr>
                    <th>${t.dateCol}</th><th>${t.particularsCol}</th>
                    <th>${t.debitCol}</th><th>${t.interestCol}</th>
                    <th>${t.creditCol}</th><th>${t.netPayableCol}</th>
                </tr></thead>
                <tbody>${ledgerRows}</tbody>
                <tfoot><tr>
                    <td colspan="2">${t.totalRow}</td>
                    <td style="color:#dc2626;">${_cur(totalDebit)}</td>
                    <td style="color:#d97706;">${_cur(totalInterest)}</td>
                    <td style="color:#059669;">${_cur(totalCredit)}</td>
                    <td style="color:#1e3a5f;">${_cur(details.totalPayable)}</td>
                </tr></tfoot>
            </table>
        </div>` : ''}

        <!-- Terms -->
        <div class="terms">
            <div class="t-title">ℹ️ ${t.termsTitle}</div>
            <ul>${t.terms.map(s => `<li>${s}</li>`).join('')}</ul>
        </div>

        <!-- Signatures -->
        <div class="sig-row">
            <div class="sig-box"><div style="height:36px;"></div><div class="sig-line"></div><div class="sig-label">${t.sigCustomer}</div></div>
            <div class="seal"><div class="seal-circle">GVF</div></div>
            <div class="sig-box"><div style="height:36px;"></div><div class="sig-line"></div><div class="sig-label">${t.sigAuth}</div></div>
        </div>

        <!-- Footer -->
        <div class="footer">
            ${t.footer}<br>
            ${t.reportTime} : &nbsp; ${nowStr}
        </div>
    </div>`;
    }

    function exportLoanPDF(loan) {
        const settings = DB.getSettings();
        const rate = loan.metalType === 'gold' ? settings.currentGoldRate : settings.currentSilverRate;
        const details = Calculator.calcLoanDetails(loan, rate);
        const lang = (typeof I18n !== 'undefined') ? I18n.getLang() : 'en';
        const title = lang === 'hi' ? `लोन रिपोर्ट — ${loan.customerName}` : `Loan Report — ${loan.customerName}`;
        const html = `<!DOCTYPE html><html><head><meta charset="UTF-8"><title>${title}</title></head><body onload="window.print()" style="margin:0;">${getLoanReportHTML(loan, details, settings, lang)}</body></html>`;
        const printWindow = window.open('', '_blank');
        printWindow.document.write(html);
        printWindow.document.close();
    }

    /**
     * Generates a PDF Blob using html2pdf
     */
    async function generateLoanPDFBlob(loan) {
        if (typeof html2pdf === 'undefined') throw new Error('html2pdf library is not loaded');
        const settings = DB.getSettings();
        const rate = loan.metalType === 'gold' ? settings.currentGoldRate : settings.currentSilverRate;
        const details = Calculator.calcLoanDetails(loan, rate);
        const lang = (typeof I18n !== 'undefined') ? I18n.getLang() : 'en';
        const container = document.createElement('div');
        container.innerHTML = getLoanReportHTML(loan, details, settings, lang);
        const cleanName = loan.customerName.replace(/\s+/g, '');
        const dateStr = new Date().toLocaleDateString('en-GB').replace(/\//g, '');
        const filename = `${cleanName}_GoldLoan_${dateStr}.pdf`;
        const opt = {
            margin: 10, filename,
            image: { type: 'jpeg', quality: 0.98 },
            html2canvas: { scale: 2, useCORS: true },
            jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
        };
        return await html2pdf().set(opt).from(container).output('blob');
    }

    /**
     * Export all loans as CSV
     */
    function exportLoansCSV() {
        const loans = DB.getLoans();
        const settings = DB.getSettings();

        const headers = [
            'Customer Name', 'Mobile', 'Metal Type', 'Purity', 'Weight (g)',
            'Loan Amount', 'Interest Rate', 'Interest Period', 'Interest Type',
            'Start Date', 'Duration (months)', 'Status', 'Locker',
            'Total Interest', 'Total Payable', 'Metal Value', 'LTV%', 'Risk Level'
        ];

        const rows = loans.map(loan => {
            const rate = loan.metalType === 'gold' ? settings.currentGoldRate : settings.currentSilverRate;
            const details = Calculator.calcLoanDetails(loan, rate);
            return [
                loan.customerName, loan.mobile || '', loan.metalType, loan.metalSubType,
                loan.weightGrams, loan.loanAmount, loan.interestRate, loan.interestPeriod,
                loan.interestType, loan.loanStartDate, loan.loanDuration, loan.status || 'active',
                loan.lockerName || '', details.totalInterest.toFixed(0),
                details.totalPayable.toFixed(0), details.metalValue.toFixed(0),
                details.ltv.toFixed(1), details.riskLevel
            ];
        });

        const csvContent = [headers, ...rows]
            .map(row => row.map(cell => `"${cell}"`).join(','))
            .join('\n');

        downloadFile(csvContent, `goldvault_loans_${new Date().toISOString().split('T')[0]}.csv`, 'text/csv');
    }

    /**
     * Download helper
     */
    function downloadFile(content, filename, mimeType) {
        const blob = new Blob([content], { type: mimeType });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    }

    /**
     * Export all data as JSON backup
     */
    function exportBackup() {
        const data = {
            loans: DB.getLoans(),
            customers: DB.getCustomers(),
            marketLog: DB.getMarketLog(),
            settings: DB.getSettings(),
            exportDate: new Date().toISOString(),
            version: '1.0'
        };

        const json = JSON.stringify(data, null, 2);
        downloadFile(json, `goldvault_backup_${new Date().toISOString().split('T')[0]}.json`, 'application/json');
    }

    /**
     * Import backup from JSON file
     */
    function importBackup(file) {
        return new Promise((resolve, reject) => {
            const reader = new FileReader();
            reader.onload = (e) => {
                try {
                    const data = JSON.parse(e.target.result);
                    if (data.loans) localStorage.setItem('gv_loans', JSON.stringify(data.loans));
                    if (data.customers) localStorage.setItem('gv_customers', JSON.stringify(data.customers));
                    if (data.marketLog) localStorage.setItem('gv_market_log', JSON.stringify(data.marketLog));
                    if (data.settings) {
                        const currentSettings = DB.getSettings();
                        localStorage.setItem('gv_settings', JSON.stringify({ ...data.settings, pin: currentSettings.pin }));
                    }
                    resolve(true);
                } catch (err) {
                    reject(err);
                }
            };
            reader.onerror = reject;
            reader.readAsText(file);
        });
    }

    return {
        exportLoanPDF, generateLoanPDFBlob, exportLoansCSV, exportBackup, importBackup
    };
})();
